import {
  ShoppingCart,
  Coffee,
  Utensils,
  Zap,
  Wifi,
  Bus,
  Fuel,
  HeartPulse,
  Scissors,
  ShoppingBag,
  Home,
  GraduationCap,
  Clapperboard,
  HeartHandshake,
  HandCoins,
  Gift,
  Plane,
  Dumbbell,
  Banknote,
  Briefcase,
  Laptop,
  PlusCircle,
  Repeat,
  ArrowLeftRight,
  Circle,
  ShoppingBasket,
  Shirt,
  Pizza,
  Carrot,
  Beef,
  Milk,
  Croissant,
  Apple,
  Smartphone,
  Globe,
  Tv,
  Film,
  Music,
  Gamepad2,
  Camera,
  BookOpen,
  School,
  PawPrint,
  Baby,
  Car,
  Bike,
  TrainFront,
  PlaneTakeoff,
  Hotel,
  Pill,
  Stethoscope,
  Shield,
  PiggyBank,
  Landmark,
  CreditCard,
  Receipt,
  TrendingUp,
  Wallet,
  Wrench,
  Droplet,
  Flame,
  Lightbulb,
  PartyPopper,
  Cake,
  Flower,
  Ticket,
  Coins,
  type LucideIcon,
} from "lucide-react";

export type CategoryKind = "INCOME" | "EXPENSE";

export interface DefaultCategory {
  name: string;
  kind: CategoryKind;
  icon: string;
}

// Seeded on every new household.
export const DEFAULT_CATEGORIES: DefaultCategory[] = [
  // Expenses
  { name: "Food", kind: "EXPENSE", icon: "shopping-cart" },
  { name: "Dining", kind: "EXPENSE", icon: "utensils" },
  { name: "Coffee", kind: "EXPENSE", icon: "coffee" },
  { name: "Utilities", kind: "EXPENSE", icon: "zap" },
  { name: "Connection", kind: "EXPENSE", icon: "wifi" }, // phone & internet
  { name: "Transport", kind: "EXPENSE", icon: "bus" },
  { name: "Fuel", kind: "EXPENSE", icon: "fuel" },
  { name: "Health", kind: "EXPENSE", icon: "heart-pulse" },
  { name: "Grooming", kind: "EXPENSE", icon: "scissors" }, // barber & salon
  { name: "Shopping", kind: "EXPENSE", icon: "shopping-bag" },
  { name: "Housing", kind: "EXPENSE", icon: "home" },
  { name: "Education", kind: "EXPENSE", icon: "graduation-cap" },
  { name: "Entertainment", kind: "EXPENSE", icon: "clapperboard" },
  { name: "Family support", kind: "EXPENSE", icon: "heart-handshake" },
  { name: "Charity", kind: "EXPENSE", icon: "hand-coins" }, // sadaqah / zakat
  { name: "Gifts", kind: "EXPENSE", icon: "gift" },
  { name: "Travel", kind: "EXPENSE", icon: "plane" },
  { name: "Fitness", kind: "EXPENSE", icon: "dumbbell" },
  // Income
  { name: "Salary", kind: "INCOME", icon: "banknote" },
  { name: "Freelance", kind: "INCOME", icon: "laptop" },
  { name: "Business", kind: "INCOME", icon: "briefcase" },
  { name: "Other income", kind: "INCOME", icon: "plus-circle" },
];

const ICONS: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  coffee: Coffee,
  utensils: Utensils,
  zap: Zap,
  wifi: Wifi,
  bus: Bus,
  fuel: Fuel,
  "heart-pulse": HeartPulse,
  scissors: Scissors,
  "shopping-bag": ShoppingBag,
  home: Home,
  "graduation-cap": GraduationCap,
  clapperboard: Clapperboard,
  "heart-handshake": HeartHandshake,
  "hand-coins": HandCoins,
  gift: Gift,
  plane: Plane,
  dumbbell: Dumbbell,
  banknote: Banknote,
  briefcase: Briefcase,
  laptop: Laptop,
  "plus-circle": PlusCircle,
  repeat: Repeat,
  transfer: ArrowLeftRight,
  circle: Circle,
  "shopping-basket": ShoppingBasket,
  shirt: Shirt,
  pizza: Pizza,
  carrot: Carrot,
  beef: Beef,
  milk: Milk,
  croissant: Croissant,
  apple: Apple,
  smartphone: Smartphone,
  globe: Globe,
  tv: Tv,
  film: Film,
  music: Music,
  gamepad: Gamepad2,
  camera: Camera,
  "book-open": BookOpen,
  school: School,
  "paw-print": PawPrint,
  baby: Baby,
  car: Car,
  bike: Bike,
  train: TrainFront,
  "plane-takeoff": PlaneTakeoff,
  hotel: Hotel,
  pill: Pill,
  stethoscope: Stethoscope,
  shield: Shield,
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  "credit-card": CreditCard,
  receipt: Receipt,
  "trending-up": TrendingUp,
  wallet: Wallet,
  wrench: Wrench,
  droplet: Droplet,
  flame: Flame,
  lightbulb: Lightbulb,
  "party-popper": PartyPopper,
  cake: Cake,
  flower: Flower,
  ticket: Ticket,
  coins: Coins,
};

export function iconFor(key: string | null | undefined): LucideIcon {
  if (!key) return Circle;
  return ICONS[key] ?? Circle;
}

// Icons offered in the category icon picker, in display order. "circle" is the
// neutral default and stays last.
export const PICKABLE_ICONS: string[] = [
  // Food & groceries
  "shopping-cart",
  "shopping-basket",
  "utensils",
  "pizza",
  "coffee",
  "croissant",
  "carrot",
  "apple",
  "beef",
  "milk",
  // Home & bills
  "home",
  "zap",
  "lightbulb",
  "droplet",
  "flame",
  "wifi",
  "smartphone",
  "globe",
  "wrench",
  "receipt",
  // Transport
  "bus",
  "car",
  "fuel",
  "bike",
  "train",
  "plane",
  "plane-takeoff",
  "hotel",
  // Health & personal
  "heart-pulse",
  "stethoscope",
  "pill",
  "shield",
  "scissors",
  "dumbbell",
  // Shopping & lifestyle
  "shopping-bag",
  "shirt",
  "gift",
  "ticket",
  "party-popper",
  "cake",
  "flower",
  // Entertainment
  "clapperboard",
  "tv",
  "film",
  "music",
  "gamepad",
  "camera",
  // Family & education
  "heart-handshake",
  "hand-coins",
  "baby",
  "paw-print",
  "graduation-cap",
  "school",
  "book-open",
  // Money & income
  "banknote",
  "wallet",
  "coins",
  "piggy-bank",
  "credit-card",
  "landmark",
  "trending-up",
  "briefcase",
  "laptop",
  "plus-circle",
  "circle",
];

// A stable Tailwind tint per icon for the little rounded category tiles.
const TONES: Record<string, string> = {
  "shopping-cart": "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
  coffee: "bg-amber-500/15 text-amber-600 dark:text-amber-400",
  utensils: "bg-red-500/15 text-red-600 dark:text-red-400",
  zap: "bg-yellow-500/15 text-yellow-600 dark:text-yellow-400",
  wifi: "bg-cyan-500/15 text-cyan-600 dark:text-cyan-400",
  bus: "bg-sky-500/15 text-sky-600 dark:text-sky-400",
  fuel: "bg-stone-500/15 text-stone-600 dark:text-stone-400",
  "heart-pulse": "bg-rose-500/15 text-rose-600 dark:text-rose-400",
  scissors: "bg-pink-500/15 text-pink-600 dark:text-pink-400",
  "shopping-bag": "bg-violet-500/15 text-violet-600 dark:text-violet-400",
  home: "bg-orange-500/15 text-orange-600 dark:text-orange-400",
  "graduation-cap": "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  clapperboard: "bg-fuchsia-500/15 text-fuchsia-600 dark:text-fuchsia-400",
  "heart-handshake": "bg-teal-500/15 text-teal-600 dark:text-teal-400",
  "hand-coins": "bg-lime-500/15 text-lime-600 dark:text-lime-400",
  gift: "bg-purple-500/15 text-purple-600 dark:text-purple-400",
  plane: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400",
  dumbbell: "bg-slate-500/15 text-slate-600 dark:text-slate-300",
  banknote: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
  briefcase: "bg-amber-600/15 text-amber-700 dark:text-amber-400",
  laptop: "bg-zinc-500/15 text-zinc-600 dark:text-zinc-300",
  "plus-circle": "bg-teal-500/15 text-teal-600 dark:text-teal-400",
  repeat: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400",
  transfer: "bg-slate-500/15 text-slate-600 dark:text-slate-300",
  circle: "bg-muted text-muted-foreground",
  "shopping-basket": "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
  shirt: "bg-violet-500/15 text-violet-600 dark:text-violet-400",
  pizza: "bg-red-500/15 text-red-600 dark:text-red-400",
  carrot: "bg-orange-500/15 text-orange-600 dark:text-orange-400",
  beef: "bg-rose-500/15 text-rose-600 dark:text-rose-400",
  milk: "bg-sky-500/15 text-sky-600 dark:text-sky-400",
  croissant: "bg-amber-500/15 text-amber-600 dark:text-amber-400",
  apple: "bg-red-500/15 text-red-600 dark:text-red-400",
  smartphone: "bg-cyan-500/15 text-cyan-600 dark:text-cyan-400",
  globe: "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  tv: "bg-violet-500/15 text-violet-600 dark:text-violet-400",
  film: "bg-fuchsia-500/15 text-fuchsia-600 dark:text-fuchsia-400",
  music: "bg-pink-500/15 text-pink-600 dark:text-pink-400",
  gamepad: "bg-purple-500/15 text-purple-600 dark:text-purple-400",
  camera: "bg-slate-500/15 text-slate-600 dark:text-slate-300",
  "book-open": "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  school: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400",
  "paw-print": "bg-amber-600/15 text-amber-700 dark:text-amber-400",
  baby: "bg-pink-500/15 text-pink-600 dark:text-pink-400",
  car: "bg-sky-500/15 text-sky-600 dark:text-sky-400",
  bike: "bg-lime-500/15 text-lime-600 dark:text-lime-400",
  train: "bg-teal-500/15 text-teal-600 dark:text-teal-400",
  "plane-takeoff": "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400",
  hotel: "bg-violet-500/15 text-violet-600 dark:text-violet-400",
  pill: "bg-rose-500/15 text-rose-600 dark:text-rose-400",
  stethoscope: "bg-teal-500/15 text-teal-600 dark:text-teal-400",
  shield: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
  "piggy-bank": "bg-pink-500/15 text-pink-600 dark:text-pink-400",
  landmark: "bg-stone-500/15 text-stone-600 dark:text-stone-400",
  "credit-card": "bg-zinc-500/15 text-zinc-600 dark:text-zinc-300",
  receipt: "bg-amber-500/15 text-amber-600 dark:text-amber-400",
  "trending-up": "bg-green-500/15 text-green-600 dark:text-green-400",
  wallet: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
  wrench: "bg-slate-500/15 text-slate-600 dark:text-slate-300",
  droplet: "bg-cyan-500/15 text-cyan-600 dark:text-cyan-400",
  flame: "bg-orange-500/15 text-orange-600 dark:text-orange-400",
  lightbulb: "bg-yellow-500/15 text-yellow-600 dark:text-yellow-400",
  "party-popper": "bg-fuchsia-500/15 text-fuchsia-600 dark:text-fuchsia-400",
  cake: "bg-pink-500/15 text-pink-600 dark:text-pink-400",
  flower: "bg-rose-500/15 text-rose-600 dark:text-rose-400",
  ticket: "bg-violet-500/15 text-violet-600 dark:text-violet-400",
  coins: "bg-amber-500/15 text-amber-600 dark:text-amber-400",
};

export function toneFor(key: string | null | undefined): string {
  if (!key) return TONES.circle;
  return TONES[key] ?? TONES.circle;
}
